import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { SunIcon } from '@heroicons/react/24/outline';
import AnimatedBackground from './components/AnimatedBackground';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Background Image */}
        <div 
          className="fixed inset-0 w-full h-full bg-cover bg-center bg-no-repeat"
          style={{
            backgroundImage: 'url("/background.jpg")',
            backgroundBlendMode: 'overlay',
            backgroundColor: 'rgba(15, 23, 42, 0.85)'
          }}
        />
        
        {/* Animated Canvas Overlay */}
        <AnimatedBackground />
        
        {/* Modern Neon Header */}
        <header className="fixed top-0 left-0 right-0 z-50 bg-transparent">
          <nav className="max-w-7xl mx-auto flex items-center justify-between h-16 px-6">
            {/* Logo */}
            <Link href="/" className="text-2xl font-extrabold text-gray-50 drop-shadow-[0_0_12px_#22d3ee]">
              DevPortfolio
            </Link>
            {/* Navigation */}
            <div className="flex items-center space-x-8">
              <button className="ml-4 p-2 rounded-full hover:bg-gray-800/60 transition-colors">
                <SunIcon className="w-6 h-6 text-yellow-400 drop-shadow-[0_0_6px_#fde68a]" />
              </button>
            </div>
          </nav>
        </header>
        <main className="pt-16 glass mx-auto max-w-4xl rounded-xl mt-8 p-8" style={{ background: "transparent"}}>
          {children}
        </main>
      </body>
    </html>
  );
}
